### ISSUE TITLE
Auto-run is happening even when "Auto-run code" and "Only auto-run code that validates" are both turned off in the settings

### ISSUE THREAD

**Issue by PodClay** [jsfiddle/jsfiddle-users#1866] opened 2024-05-25 02:50 UTC
This seems to have been going on for a few years!  See [Issue #1615](https://github.com/jsfiddle/jsfiddle-users/issues/1615) and [Issue #1739](https://github.com/jsfiddle/jsfiddle-users/issues/1739)
Using Chrome Version 125.0.6422.77 (Official Build) (64-bit) on Windows

**Comment by oskarkrawczyk** [comment] 2024-05-25 05:38
@PodClay This has been reported but not once could reproduce this behavior.

Testing on Chrome, both auto-run options are turned, code never runs automatically.

I have no clue why this might be happening to some people – if you could provide the output of `EditorUISettings` var when you paste in into your webdev console while being on jsfiddle.net.

**Comment by oskarkrawczyk** [comment] 2024-07-06 13:10
Closing due to lack of followup info.

**Closed by oskarkrawczyk** 2024-07-06 13:10 UTC
Labels: Can't replicate, Requires more info
