### ISSUE TITLE
/show doesn't work now

### ISSUE THREAD

**Issue by Crayder** [jsfiddle/jsfiddle-users#1885] opened 2024-09-11 19:32 UTC
I used to always do tests and share my fiddles with the /show link (ex `https://jsfiddle.net/Craydeh/es3zyqLt/show`).

Before, this would produce a cleaner full-screen layout which was much more useful for testing some things. Particularly when testing CSS layouts and such. Now, we just get a 404? Surely this is a mistake!?

![image](https://github.com/user-attachments/assets/0bd2585b-c674-40ff-be05-bcd00a973d7f)

**Comment by oskarkrawczyk** [comment] 2024-09-11 20:01
Duplicate of #1864

**Closed by oskarkrawczyk** 2024-09-11 20:01 UTC
